name: syncfusion_flutter_calendar
description: The Syncfusion Flutter Calendar widget has built-in configurable views that provide basic functionalities for scheduling and representing appointments/events efficiently.
version: 18.3.35
homepage: https://github.com/syncfusion/flutter-widgets/tree/master/packages/syncfusion_flutter_calendar

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  timezone: 0.5.7
  syncfusion_flutter_core:
  syncfusion_flutter_datepicker:
  intl: ">=0.15.0 <0.17.0"

flutter:
  assets:
    - packages/timezone/data/2020a.tzf