name: syncfusion_flutter_maps
description: Syncfusion Flutter Maps is a data visualization library written natively in Dart for creating beautiful and customizable maps.
version: 18.3.35-beta
homepage: https://github.com/syncfusion/flutter-widgets/tree/master/packages/syncfusion_flutter_maps

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  syncfusion_flutter_core:

  collection: ">=1.9.0 <1.16.0"
  http: ^0.12.2

flutter:
