name: syncfusion_flutter_signaturepad
description: The Signature Pad widget allows you to capture smooth and more realistic signatures through drawn gestures and save it as an image.
version: 18.3.35-beta
homepage: https://github.com/syncfusion/flutter-widgets/tree/master/packages/syncfusion_flutter_signaturepad

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  syncfusion_flutter_core:

flutter:
